import React, { CSSProperties } from 'react';

/* style this button using CSS props */
export const Button = () => {
  /*
   * these css props were generated by the `createTheme` funciton. They are made available in the page by the generated Theme component.
   */
  const myStyle: CSSProperties = {
    backgroundColor: "var(--primary-color-background)",
    color: "var(--primary-color-text)",
    padding: "var(--button-padding-medium)",
    fontWeight: "var(--button-font-weight)",
  };
  return <button style={myStyle}>A Button Styled using CSS Props</button>;
};
