export const defaultFontTokenValues = {
  // display - large
  mdSysTypescaleDisplayLargeFontFamilyName: "Roboto",
  mdSysTypescaleDisplayLargeFontFamilyStyle: "Regular",
  mdSysTypescaleDisplayLargeFontWeight: "400",
  mdSysTypescaleDisplayLargeFontSize: "57px",
  mdSysTypescaleDisplayLargeLineHeight: "64px",
  mdSysTypescaleDisplayLargeLetterSpacing: "-0.25px",
  // display - medium
  mdSysTypescaleDisplayMediumFontFamilyName: "Roboto",
  mdSysTypescaleDisplayMediumFontFamilyStyle: "Regular",
  mdSysTypescaleDisplayMediumFontWeight: "400",
  mdSysTypescaleDisplayMediumFontSize: "45px",
  mdSysTypescaleDisplayMediumLineHeight: "52px",
  mdSysTypescaleDisplayMediumLetterSpacing: "0px",
  // display - small
  mdSysTypescaleDisplaySmallFontFamilyName: "Roboto",
  mdSysTypescaleDisplaySmallFontFamilyStyle: "Regular",
  mdSysTypescaleDisplaySmallFontWeight: "400",
  mdSysTypescaleDisplaySmallFontSize: "36px",
  mdSysTypescaleDisplaySmallLineHeight: "44px",
  mdSysTypescaleDisplaySmallLetterSpacing: "0px",
  // headline - large
  mdSysTypescaleHeadlineLargeFontFamilyName: "Roboto",
  mdSysTypescaleHeadlineLargeFontFamilyStyle: "Regular",
  mdSysTypescaleHeadlineLargeFontWeight: "400",
  mdSysTypescaleHeadlineLargeFontSize: "32px",
  mdSysTypescaleHeadlineLargeLineHeight: "40px",
  mdSysTypescaleHeadlineLargeLetterSpacing: "0px",
  // headline - medium
  mdSysTypescaleHeadlineMediumFontFamilyName: "Roboto",
  mdSysTypescaleHeadlineMediumFontFamilyStyle: "Regular",
  mdSysTypescaleHeadlineMediumFontWeight: "400",
  mdSysTypescaleHeadlineMediumFontSize: "28px",
  mdSysTypescaleHeadlineMediumLineHeight: "36px",
  mdSysTypescaleHeadlineMediumLetterSpacing: "0px",
  // headline - small
  mdSysTypescaleHeadlineSmallFontFamilyName: "Roboto",
  mdSysTypescaleHeadlineSmallFontFamilyStyle: "Regular",
  mdSysTypescaleHeadlineSmallFontWeight: "400",
  mdSysTypescaleHeadlineSmallFontSize: "24px",
  mdSysTypescaleHeadlineSmallLineHeight: "32px",
  mdSysTypescaleHeadlineSmallLetterSpacing: "0px",
  // body - large
  mdSysTypescaleBodyLargeFontFamilyName: "Roboto",
  mdSysTypescaleBodyLargeFontFamilyStyle: "Regular",
  mdSysTypescaleBodyLargeFontWeight: "400",
  mdSysTypescaleBodyLargeFontSize: "16px",
  mdSysTypescaleBodyLargeLineHeight: "24px",
  mdSysTypescaleBodyLargeLetterSpacing: "0.50px",
  // body - medium
  mdSysTypescaleBodyMediumFontFamilyName: "Roboto",
  mdSysTypescaleBodyMediumFontFamilyStyle: "Regular",
  mdSysTypescaleBodyMediumFontWeight: "400",
  mdSysTypescaleBodyMediumFontSize: "14px",
  mdSysTypescaleBodyMediumLineHeight: "20px",
  mdSysTypescaleBodyMediumLetterSpacing: "0.25px",
  // body - small
  mdSysTypescaleBodySmallFontFamilyName: "Roboto",
  mdSysTypescaleBodySmallFontFamilyStyle: "Regular",
  mdSysTypescaleBodySmallFontWeight: "400",
  mdSysTypescaleBodySmallFontSize: "12px",
  mdSysTypescaleBodySmallLineHeight: "16px",
  mdSysTypescaleBodySmallLetterSpacing: "0.40px",
  // label - large
  mdSysTypescaleLabelLargeFontFamilyName: "Roboto",
  mdSysTypescaleLabelLargeFontFamilyStyle: "Medium",
  mdSysTypescaleLabelLargeFontWeight: "500",
  mdSysTypescaleLabelLargeFontSize: "14px",
  mdSysTypescaleLabelLargeLineHeight: "20px",
  mdSysTypescaleLabelLargeLetterSpacing: "0.10px",
  // label - medium
  mdSysTypescaleLabelMediumFontFamilyName: "Roboto",
  mdSysTypescaleLabelMediumFontFamilyStyle: "Medium",
  mdSysTypescaleLabelMediumFontWeight: "500",
  mdSysTypescaleLabelMediumFontSize: "12px",
  mdSysTypescaleLabelMediumLineHeight: "16px",
  mdSysTypescaleLabelMediumLetterSpacing: "0.50px",
  // label - small
  mdSysTypescaleLabelSmallFontFamilyName: "Roboto",
  mdSysTypescaleLabelSmallFontFamilyStyle: "Medium",
  mdSysTypescaleLabelSmallFontWeight: "500",
  mdSysTypescaleLabelSmallFontSize: "11px",
  mdSysTypescaleLabelSmallLineHeight: "16px",
  mdSysTypescaleLabelSmallLetterSpacing: "0.50px",
  // title - large
  mdSysTypescaleTitleLargeFontFamilyName: "Roboto",
  mdSysTypescaleTitleLargeFontFamilyStyle: "Regular",
  mdSysTypescaleTitleLargeFontWeight: "400",
  mdSysTypescaleTitleLargeFontSize: "22px",
  mdSysTypescaleTitleLargeLineHeight: "28px",
  mdSysTypescaleTitleLargeLetterSpacing: "0px",
  // title - medium
  mdSysTypescaleTitleMediumFontFamilyName: "Roboto",
  mdSysTypescaleTitleMediumFontFamilyStyle: "Medium",
  mdSysTypescaleTitleMediumFontWeight: "500",
  mdSysTypescaleTitleMediumFontSize: "16px",
  mdSysTypescaleTitleMediumLineHeight: "24px",
  mdSysTypescaleTitleMediumLetterSpacing: "0.15px",
  // title - small
  mdSysTypescaleTitleSmallFontFamilyName: "Roboto",
  mdSysTypescaleTitleSmallFontFamilyStyle: "Medium",
  mdSysTypescaleTitleSmallFontWeight: "500",
  mdSysTypescaleTitleSmallFontSize: "14px",
  mdSysTypescaleTitleSmallLineHeight: "20px",
  mdSysTypescaleTitleSmallLetterSpacing: "0.10px",
};
